### ISSUE TITLE
computed properties no cache?

### ISSUE THREAD

**Issue by tylerlong** [nx-js/observer-util#46]
https://github.com/tylerlong/choose-a-state-container/blob/master/cache/observer-util.spec.js#L24

It should have cache. Otherwise what's the point of a computed property? It is just a normal method without cache.

Like the reselect sample: https://github.com/tylerlong/choose-a-state-container/blob/master/cache/redux.spec.js#L40

And the SubX sample: https://github.com/tylerlong/choose-a-state-container/blob/master/cache/subx.spec.js#L24

**Comment by solkimicreb** [comment]
> Otherwise what's the point of a computed property?

What's the point of pain JS property getters? They are syntactic sugar.

This is a very purposeful design decision, not an oversight. I am using this lib and never had perf issues because of the lack of caching. On the other hand auto-caching all getters can cause really painful bugs. Cache clearing is a subtle art and it is usually use-case specific, you can quickly end up with a stuck cache when the getter uses some dependencies that only you know about and the lib can not track (like reading from LocalStorage).

Most getters are super simple and they are not worth the caching hustle, if you have large getters and computed properties it's up to you to properly cache them an avoid these pitfalls. I honestly think caching can not be properly generalized.

Did you run into an actual performance issue with the lib or is this just a precautionary conversation?

**Comment by tylerlong** [comment]
When I google "computed property", almost all the results are about Vue.js. And Vue.js's computed property does support cache out of the box. So I assume that computed property is "getter function + caching". A getter function without cache is just a getter function, it should not be called a computed property.

I might be wrong though.

**Comment by solkimicreb** [comment]
I think computed properties are properties that are computed from other data (meaning they are simple getters). It's unfortunate that the google results are so tightly coupled with caching but I don't want to mislead people. I changed all "computed properties" to "getters/setters" in both the observer-util and react-easy-state docs.

I do not plan to add caching to the lib without a very good reason though. I will close this now, feel free to reopen if needed.
